
player = input("Hello! what is your name?: ")
print("Welcome " + player + " to my Mad Libs game!")
length = input("Would you like a romantic or funny story?: ")

if length == "romantic":
    print("Great! please follow the prompts and enjoy!")
    adjective1 = input("Enter adjective: ")
    adjective2 = input("Enter another adjective: ")
    body_part = input("Enter a body part: ")
    noun1 = input("Enter a noun: ")
    animal = input("Enter an animal: ")
    verb1 = input("Enter a verb: ")
    adverb1 = input("Enter an adverb: ")
    noun2 = input("Enter a noun: ")
    adjective3 = input("Enter an adjective: ")
    noun3 = input("Enter a noun: ")
    verb2 = input("Enter a verb: ")
    noun4 = input("Enter a noun: ")
    body_part2 = input("Enter a body part: ")
    noun5 = input("Enter a noun: ")
    adverb2 = input("Enter an adverb: ")
    verb3 = input("Enter a verb: ")
    verb4 = input("Enter another verb: ")
    exclamation = input("Enter an exclamation: ")
    verb_past_tense = input("Enter a past tense verb: ")
    verb_past_tense2 = input("Enter another past tense verb: ")
    number = input("Enter a number: ")
    number2 = input("Enter another number: ")
    verb5 = input("Enter a verb: ")
    verb6 = input("Enter another verb: ")
    verb7 = input("Enter one last verb: ")
    yes = input("Great all finished! are you ready to hear the story?: ")
    print(" ")
    print(" ")
    print("When we first met, you looked " + adjective1 + " and " + adjective2 + ".")
    print("I couldn't believe my " + body_part + "!")
    print("You smelled like " + noun1 + " and walked as graceful as a " + animal + ".")
    print("I couldn't wait to " + verb1 + " to you.")
    print(" ")
    print("I " + adverb1 + " asked you if i could have your " + noun2 + ".")
    print("I could see the look of " + adjective3 + " in your eyes.")
    print("You hesitated for a moment, then gave me a " + noun3 + ".")
    print(" ")
    print("I finally got to take you on our first date. I loved spending time")
    print("with you. You could make me " + verb2 + " so easily, like no one had before")
    print("When you touched me, I felt " + noun4 + " up my " + body_part2 + ".")
    print("When you looked at me, I could see " + noun5 + ".")
    print("I knew we were meant to be together.")
    print(" ")
    print("After a " + adverb2 + " night, I was so " + verb3 + " to bring you home.")
    print("I longed to " + verb4 + " you again. You looked at me and")
    print("said \"" + exclamation + "\" and i just knew. You " + verb_past_tense)
    print("me and i " + verb_past_tense2 + " you.")
    print(" ")
    print("Here we are after all this time. It feels like it's been")
    print(number + " years! I look forward to " + number2 + " more.")
    print("You make me want to " + verb5 + " and i will " + verb6 + " you forever.")
    print("Nobody else could " + verb7 + " me, like you do.")


if length == "funny":
    adjective1 = input("Enter adjective: ")
    adjective2 = input("Enter another adjective: ")
    type_of_bird = input("Enter a type of bird: ")
    room = input("Enter a room in a house: ")
    verb_past_tense = input("Enter a past tense verb: ")
    verb = input("Enter a verb: ")
    relatives_name = input("Enter a relatives name: ")
    noun = input("Enter a noun: ")
    liquid = input("Enter a liquid: ")
    body_part = input("Enter a body part(plural): ")
    noun2 = input("Enter a noun(plural): ")
    verb2 = input("Enter a verb ending in -ing: ")
    noun3 = input("Enter another noun: ")
    print(" ")
    yes = input("Great! are you ready to hear the story?: ")
    print(" ")
    print("It was a " + adjective1 + " cold November day.")
    print("I woke up to the " + adjective2 + " smell of " + type_of_bird)
    print("roasting in the " + room + " downstairs.")
    print("I " + verb_past_tense + " down the stairs to see")
    print("if i could help " + verb + " dinner.")
    print("My mom said, \"see if " + relatives_name + " needs a fresh " + noun + ".\"")
    print("So I carried a tray of glasses full of " + liquid + " into the room.")
    print("When i got there, I couldn't believe my " + body_part + "!")
    print("There were " + noun2 + verb2 + " on the " + noun3 + "!")